server:
  port: 9002
spring:
  application:
    name: springboot-file
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      location: uploadfile/
